"""
Match Preview Service - Thin DB read layer for pre-generated match previews.
Previews are generated by the standalone script (scripts/generate_match_previews.py)
and stored in the match_previews table.
"""
import logging
from typing import Optional

from sqlalchemy import case

from app.data.database import get_session
from app.data.models import MatchPreview

logger = logging.getLogger(__name__)


def get_preview(squiggle_id: int) -> Optional[str]:
    """Get best available preview — prefers gameday over early."""
    try:
        with get_session() as session:
            preview = (
                session.query(MatchPreview)
                .filter(MatchPreview.squiggle_game_id == squiggle_id)
                .order_by(
                    case(
                        (MatchPreview.preview_type == "gameday", 0),
                        else_=1,
                    )
                )
                .first()
            )
            return preview.preview_text if preview else None
    except Exception as e:
        logger.debug(f"Failed to get preview for game {squiggle_id}: {e}")
        return None


def get_all_previews(squiggle_ids: list[int]) -> dict[int, str]:
    """Batch fetch previews for multiple matches.

    Returns {squiggle_id: preview_text}, preferring gameday over early.
    """
    if not squiggle_ids:
        return {}

    try:
        with get_session() as session:
            previews = (
                session.query(MatchPreview)
                .filter(MatchPreview.squiggle_game_id.in_(squiggle_ids))
                .order_by(
                    MatchPreview.squiggle_game_id,
                    case(
                        (MatchPreview.preview_type == "gameday", 0),
                        else_=1,
                    ),
                )
                .all()
            )

            result: dict[int, str] = {}
            for preview in previews:
                # First seen per game wins (gameday sorted first)
                if preview.squiggle_game_id not in result:
                    result[preview.squiggle_game_id] = preview.preview_text

            return result
    except Exception as e:
        logger.debug(f"Failed to batch fetch previews: {e}")
        return {}
