"""
AFL Analytics Agent - State Schema

Defines the state that flows through the LangGraph workflow.
"""
from typing import TypedDict, Optional, List, Dict, Any
from enum import Enum


class WorkflowStep(str, Enum):
    """Agent workflow steps."""
    CLASSIFY_RESOLVE = "classify_resolve"  # Milestone 3a+
    RETRIEVE_CONTEXT = "retrieve_context"  # Milestone 3b+
    GENERATE_SQL = "generate_sql"  # Milestone 3b+
    DIAGNOSE_EMPTY = "diagnose_empty"  # Milestone 3c+
    REVIEW = "review"  # Milestone 3d+
    ANALYZE_DEPTH = "analyze_depth"
    PLAN = "plan"
    EXECUTE = "execute"
    VISUALIZE = "visualize"
    RESPOND = "respond"


class QueryIntent(str, Enum):
    """Types of queries the agent can handle."""
    SIMPLE_STAT = "simple_stat"  # "Who won the 2024 grand final?", "Who won last night?"
    PLAYER_COMPARISON = "player_comparison"  # "Compare Cripps vs Oliver"
    TEAM_ANALYSIS = "team_analysis"  # "Show Collingwood's scoring trend"
    TREND_ANALYSIS = "trend_analysis"  # "Max Gawn's hitout average over time"
    AFL_NEWS = "afl_news"  # "What's the latest AFL news?"
    INJURY_NEWS = "injury_news"  # "Any injuries for Collingwood?"
    TIPPING_ADVICE = "tipping_advice"  # "Who should I tip in Collingwood v Adelaide?"
    UNKNOWN = "unknown"


class AgentState(TypedDict, total=False):
    """
    State object that flows through the LangGraph workflow.

    Workflow progression:
    1. CLASSIFY_RESOLVE: Classify turn type, resolve entities deterministically
    2. RETRIEVE_CONTEXT: Prune schema docs + pick verified SQL examples
    3. GENERATE_SQL: One LLM call — final intent + SQL
    4. ANALYZE_DEPTH / PLAN: Determine analysis mode and steps
    5. EXECUTE: Run SQL queries and calculations
    6. DIAGNOSE_EMPTY / REVIEW: Explain 0 rows / sanity-check results
    7. VISUALIZE: Generate chart specifications (if needed)
    8. RESPOND: Format natural language response
    """
    # Input
    user_query: str
    conversation_id: Optional[str]

    # Understanding phase
    intent: Optional[QueryIntent]
    entities: Dict[str, Any]  # {players: [...], teams: [...], seasons: [...], metrics: [...]}
    needs_clarification: bool
    clarification_question: Optional[str]
    warnings: List[str]  # Non-fatal warnings surfaced during processing (e.g. entity resolution mismatches)

    # Planning phase
    analysis_plan: List[str]  # Step-by-step plan
    requires_visualization: bool
    chart_type: Optional[str]  # "line", "bar", "scatter", etc.
    fallback_approach: Optional[str]  # Simplified approach if complex query

    # Enhanced statistics
    analysis_mode: Optional[str]  # "summary" or "in_depth"
    analysis_types: List[str]  # ["average", "trend", "comparison", "rank"]
    context_insights: Dict[str, Any]  # Historical context, form analysis, venue splits
    data_quality: Dict[str, Any]  # Sample size, confidence, warnings
    stats_summary: Dict[str, Any]  # Formatted statistics for GPT consumption

    # Execution phase
    sql_query: Optional[str]
    sql_validated: bool
    query_results: Optional[Any]  # Pandas DataFrame
    statistical_analysis: Dict[str, Any]
    execution_error: Optional[str]
    pre_generated_sql: Optional[str]  # SQL generated by the generate_sql node (executed by execute_node)
    llm_chart_type_hint: Optional[str]  # Chart type suggested by the generate_sql LLM call
    llm_chart_config_hint: Optional[Dict]  # x_col_hint, y_col_hint from the generate_sql LLM call

    # Visualization phase
    visualization_spec: Optional[Dict]  # Plotly JSON spec

    # Response phase
    natural_language_summary: str
    confidence: float  # 0.0 to 1.0
    sources: List[str]  # Data source references

    # Metadata
    current_step: WorkflowStep
    thinking_message: Optional[str]  # User-facing status update
    errors: List[str]
    socketio_emit: Optional[Any]  # Callback for emitting WebSocket progress updates
    conversation_history: Optional[List[Dict[str, Any]]]  # Recent conversation messages for context
    token_usage: Dict[str, int]  # Accumulated real OpenAI usage for this request: {"input_tokens": int, "output_tokens": int}

    # ── Milestone 3+ (classify_resolve → retrieve_context → generate_sql → execute → diagnose_empty/review → visualize → respond) ──
    turn_type: Optional[str]  # "new_question" | "follow_up" | "correction" | "clarification_answer" | "chitchat" (set by classify_resolve)
    bypass_cache: bool  # True when this turn should skip cache READS (LLM-understanding cache + SQL result cache) — set for corrections so a stale cached answer isn't re-served. Still WRITES to cache as normal.
    sql_attempts: int  # Number of SQL generation/execution attempts this turn (self-correction retries in generate_sql, M3b+)
    prior_sql: Optional[str]  # Previous turn's persisted SQL, loaded when turn_type == "correction" (see conversation metadata)
    prior_row_count: Optional[int]  # Previous turn's persisted row count, loaded alongside prior_sql
    prior_answer: Optional[str]  # Previous turn's assistant response text, loaded alongside prior_sql
    complaint_summary: Optional[str]  # One-sentence summary of what the user says was wrong (turn_type == "correction")
    diagnosis: Optional[Dict[str, Any]]  # Output of diagnose_empty node (M3c+): why a query returned 0 rows, and whether it's fixable
    review_verdict: Optional[Dict[str, Any]]  # Output of review node (M3d+): {"verdict": "YES"|"NO", "reason": str} — sanity check that non-empty query_results actually answer user_query. Self-clears (set back to None) once consumed by a review-driven generate_sql retry.
    review_regenerated: bool  # True once `review` has triggered ONE generate_sql regen this turn — prevents review from looping back more than once (mirrors diagnose_regenerated).
    review_should_regenerate: bool  # Ephemeral flag set by review_node and read immediately by the post-review router (not meaningful outside that single hop) — mirrors diagnose_should_regenerate.

    # ── Milestone 3b: retrieve_context → generate_sql ──
    retrieved_schema_docs: Optional[str]  # Pruned per-table schema docs for this query (app/agent/schema_docs.py), set by retrieve_context
    retrieved_examples: List[Dict[str, Any]]  # Top-k verified SQL examples for this query (app/agent/sql_examples.py), set by retrieve_context
    conversation_snippet: Optional[str]  # Short textual summary of recent turns, set by retrieve_context, consumed by generate_sql's prompt

    # ── Milestone 3c: self-correct loop (execute→generate_sql) + diagnose_empty ──
    sql_error: Optional[str]  # Raw DB error message from the most recent execute attempt. When set, the post-execute router sends this turn back to generate_sql with the exact error + failed_sql (self-correct loop); cleared at the start of every fresh execute attempt.
    failed_sql: Optional[str]  # The SQL that produced sql_error, fed back into generate_sql's retry prompt verbatim.
    diagnose_regenerated: bool  # True once diagnose_empty has triggered ONE generate_sql regen this turn — prevents diagnose_empty from looping back more than once.
    diagnose_should_regenerate: bool  # Ephemeral flag set by diagnose_empty_node and read immediately by the post-diagnose router (not meaningful outside that single hop).
